version: "3.8"

services:
  streamlit-app:
    container_name: finance-assistant
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
    env_file:
      - .env
    volumes:
      - ./app:/app
