rag:
  embedder: "BAAI/bge-base-en-v1.5"
  responder: "models/gemini-1.5-flash"
  qdrant_url: "http://localhost:6333"
  top_k: 3

parsing:
  llmsherpa_api_url: "http://localhost:5010/api/parseDocument?renderFormat=all"